all:
	pdflatex DeepRLAlgorithms.tex
	pdflatex DeepRLAlgorithms.tex
	bibtex sample-base # remove if no references/bibliography
	pdflatex DeepRLAlgorithms.tex # remove if no references/bibliography

clean:
	rm -f *.pdf *.aux *.log *.toc *.blg *.out *.bbl
